### ISSUE TITLE
Another 2021.2.0b1 headsup: Error adding entities for domain binary_sensor with platform blueiris

### ISSUE THREAD

**Issue by BoneheadFraggle** [elad-bar/ha-blueiris#100]
Last known working HA version: 2021.1.5

Now running HA 2021.2.0b1 + BlueIris NVR 1.0.1:
I have two of those in the logs after every restart. I can't figure out which `binary_sensor` it refers to. 

```
2021-01-31 09:57:01 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform blueiris
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/blueiris/models/base_entity.py", line 102, in async_added_to_hass
    await self.async_added_to_hass_local()
  File "/config/custom_components/blueiris/binary_sensors/main.py", line 40, in async_added_to_hass_local
    f"Subscribing to MQTT topics '{MQTT_ALL_TOPIC}', QOS: {DEFAULT_QOS}"
NameError: name 'DEFAULT_QOS' is not defined
```

96 binary_sensors are created; 
five binary sensors per camera (audio, connectivity, dio, external, motion) x 19 cameras = 95 sensors.
95 + "binary_sensor.blueiris_alerts" = 96.
Read the documentation and that seems to be correct.

I'd be glad to provide more info.

**Comment by FuzzyMistborn** [comment]
Seeing this on 2021.1.x when running v. 1.0.1 of the component so it's not related to the beta.  Rolling back to 1.0 for now as this bug seems to kill any alerts.

**Comment by elad-bar** [comment]
Will fix it later today
