### ISSUE TITLE
Unable to install integration "Config Flow could not be loaded"

### ISSUE THREAD

**Issue by aidbish** [elad-bar/ha-blueiris#114]
Hi

I had to remove the integration due to a new BI server install
Upon deleting and trying to setup the integration i get an error

"Config Flow could not be loaded"
i have cleared my .storage folder of the blue iris file, i heave cleaned my config entries and core  files of any previous blue iris integration references but still persists.

i have deleted and re-downloded the custom components files manually just in case hacs was the issue, this still persists

Other integrations can be installed

Error from the log

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 178, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 127, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 39, in async_step_user
    await self._config_flow.initialize(self.hass)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 63, in initialize
    await self.update_data(data, CONFIG_FLOW_INIT)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 97, in update_data
    await self._update_entry()
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 238, in _update_entry
    entry = ConfigEntry(
TypeError: __init__() got multiple values for argument 'options'

**Comment by aidbish** [comment]
Forgot was running dev version, rolled back to beta and all ok
