### ISSUE TITLE
No moduled named 'av' after latest HA upgrade to 2021.7

### ISSUE THREAD

**Issue by MarkHofmann11** [elad-bar/ha-blueiris#118]
2021-07-07 18:25:35 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-07 18:25:37 ERROR (MainThread) [homeassistant.setup] Setup failed for cloud: Unable to import component: No module named 'av'
2021-07-07 18:25:38 ERROR (MainThread) [homeassistant.setup] Setup failed for camera: Unable to import component: No module named 'av'
2021-07-07 18:25:39 ERROR (MainThread) [homeassistant.setup] Setup failed for google_assistant: Unable to import component: No module named 'av'
2021-07-07 18:25:40 ERROR (MainThread) [homeassistant.setup] Setup failed for mobile_app: Unable to import component: No module named 'av'
2021-07-07 18:25:40 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of blueiris. Setup failed for dependencies: camera
2021-07-07 18:25:40 ERROR (MainThread) [homeassistant.setup] Setup failed for blueiris: Could not set up all dependencies.
2021-07-07 18:25:49 ERROR (MainThread) [homeassistant.components.konnected.panel] Exception trying to get panel status: 
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration axis: No module named 'av'
2021-07-07 18:26:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "d:\homeassistant\lib\site-packages\homeassistant\config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "d:\homeassistant\lib\site-packages\homeassistant\loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "d:\homeassistant\lib\site-packages\homeassistant\loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "d:\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\homeassistant\lib\site-packages\homeassistant\components\axis\__init__.py", line 10, in <module>
    from .const import DOMAIN as AXIS_DOMAIN
  File "d:\homeassistant\lib\site-packages\homeassistant\components\axis\const.py", line 5, in <module>
    from homeassistant.components.camera import DOMAIN as CAMERA_DOMAIN
  File "d:\homeassistant\lib\site-packages\homeassistant\components\camera\__init__.py", line 30, in <module>
    from homeassistant.components.stream import Stream, create_stream
  File "d:\homeassistant\lib\site-packages\homeassistant\components\stream\__init__.py", line 46, in <module>
    from .recorder import RecorderOutput
  File "d:\homeassistant\lib\site-packages\homeassistant\components\stream\recorder.py", line 10, in <module>
    import av
ModuleNotFoundError: No module named 'av'

**Comment by MarkHofmann11** [comment]
FYI - Looks like there is a pull request on HA to fix the issue which is apparently effecting several custom components.

https://github.com/home-assistant/core/issues/52644

**Comment by elad-bar** [comment]
Hi, not sure why you think it's related to this component, it failed loading axis
