### ISSUE TITLE
Installation of blue iris nvr failing

### ISSUE THREAD

**Issue by koenvo27** [elad-bar/ha-blueiris#119]
Hello there,

I'm quite new to Hassio and trying to setup BlueIris NVR throught HACS.

I can install the repository via hacs, so far so good.. (tried multiple versions)

But then i go to configuration - integrations and blue iris aint there. When I try to add it from there. I can see it but when i try to add it i get the following message:

------------------------------------------
Error
Config flow could not be loaded
------------------------------------------

Can someone help me out please?

Thanks in advance.

K.

**Comment by koenvo27** [comment]
I get this error in the logs also:

Logger: aiohttp.server
Source: custom_components/blueiris/managers/config_flow_manager.py:238
Integration: Blue Iris NVR (documentation)
First occurred: 12:11:54 (1 occurrences)
Last logged: 12:11:54

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 127, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 39, in async_step_user
    await self._config_flow.initialize(self.hass)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 63, in initialize
    await self.update_data(data, CONFIG_FLOW_INIT)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 97, in update_data
    await self._update_entry()
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 238, in _update_entry
    entry = ConfigEntry(
TypeError: __init__() got multiple values for argument 'options'

**Comment by koenvo27** [comment]
Update of hassio and components did the trick.
