### ISSUE TITLE
Support for Hardwired Translator for  IQ Hardwire 16-S

### ISSUE THREAD

**Issue by gilperme** [elad-bar/ha-blueiris#128]
Just wanted to report that the hardwired translator used with the Qolsys panel in systems where you takeover existing alarm systems is not supported by the integration. I think this is just about creating the sensor, but not familiar enough to put pieces together. I'm including the debug logs below so please let me know if you need anything else to support this. Thanks!

>>>>HA Log with MQTT Payload while creating sensors

`2021-10-15 19:10:52 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'name': 'Hardwire Translator', 'device_class': '', 'state_topic': 'mqtt-states/binary_sensor/hardwire_translator/state', 'payload_on': 'Open', 'payload_off': 'Closed', 'availability_mode': 'all', 'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'mqtt-availability/binary_sensor/hardwire_translator/availability'}, {'payload_available': 'online', 'payload_not_available': 'mqtt-client/status', 'topic': 'mqtt-client/status'}], 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 180, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value must be one of ['battery', 'battery_charging', 'cold', 'connectivity', 'door', 'garage_door', 'gas', 'heat', 'light', 'lock', 'moisture', 'motion', 'moving', 'occupancy', 'opening', 'plug', 'power', 'presence', 'problem', 'safety', 'smoke', 'sound', 'update', 'vibration', 'window'] for dictionary value @ data['device_class']`

>>>Parsed JSON from AppDaemon Log while creating sensors
I cutout the other sensors that are supported

`{
  "event": "INFO",
  "info_type": "SUMMARY",
  "nonce": "qolsys",
  "partition_list": [
    {
      "name": "partition1",
      "partition_id": 0,
      "secure_arm": false,
      "status": "DISARM",
      "zone_list": [
        {
          "group": "takeovermodule",
          "id": "23E1A0",
          "name": "Hardwire Translator",
          "partition_id": 0,
          "state": "0",
          "status": "Closed",
          "type": "TakeoverModule",
          "zone_alarm_type": 0,
          "zone_id": 4,
          "zone_physical_type": 13,
          "zone_type": 18
        },
]
    }
  ],
  "requestID": "df050003-2239-476f-8403-de0f8cfaf9fe"
}`

**Comment by gilperme** [comment]
apologies, this issue was meant for another repo.  Thanks.
