### ISSUE TITLE
Integration stopped working after update to 2022.3.3

### ISSUE THREAD

**Issue by Schlbuditz** [elad-bar/ha-blueiris#159]
From the log, three different errors:

```
"Felet härrör från en anpassad integration.

Logger: custom_components.blueiris.managers.home_assistant
Source: custom_components/blueiris/managers/home_assistant.py:209
Integration: Blue Iris NVR (documentation)
First occurred: 15:57:48 (3 occurrences)
Last logged: 15:58:11

Failed to async_update, Error: can only concatenate str (not "int") to str, Line: 201"
```

```
"Felet härrör från en anpassad integration.

Logger: aiohttp.server
Source: custom_components/blueiris/managers/config_flow_manager.py:132
Integration: Blue Iris NVR (documentation)
First occurred: 15:57:16 (2 occurrences)
Last logged: 15:57:20

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 201, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 93, in async_step_init
    return await self.async_step_blue_iris_additional_settings(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 125, in async_step_blue_iris_additional_settings
    schema = self._config_flow.get_default_options()
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 132, in get_default_options
    camera_list: List[CameraData] = ha.api.camera_list
AttributeError: 'NoneType' object has no attribute 'api'"
```

```
"Felet härrör från en anpassad integration.

Logger: custom_components.blueiris
Source: custom_components/blueiris/__init__.py:40
Integration: Blue Iris NVR (documentation)
First occurred: 15:57:02 (1 occurrences)
Last logged: 15:57:02

Failed to load BlueIris, error: Unable to find service logger.set_level, line: 27"
```

I have tried to reinstall Blue Iris NVR in HACS and deleted/reinstalled the integration but the same errors comes up. No change has been made at the Blue Iris server.

**Comment by kramttocs** [comment]
For some reason github dropped the 1.0.12 release that fixes this error. I just republished it. Please 'Update Information' in HACS for the integration and take the update. 
Let me know if you are back working and I will close this if so.
Thanks

**Comment by Schlbuditz** [comment]
> For some reason github dropped the 1.0.12 release that fixes this error. I just republished it. Please 'Update Information' in HACS for the integration and take the update. Let me know if you are back working and I will close this if so. Thanks

That did the trick, thanks! All good now

**Comment by kramttocs** [comment]
Thanks. I have no idea why that release disappeared. It even shows that it was done 4 days ago :)

Glad you are back up!
