### ISSUE TITLE
No module named 'custom.components.None.recorder'

### ISSUE THREAD

**Issue by WolfsWelpe** [elad-bar/ha-blueiris#174]
Hello,

I'm encountering an error while booting up:
`2022-06-19 13:44:01 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing blueiris/recorder.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.None.recorder'`

Not sure what it is, Does anyone have any ideas?

**Comment by kramttocs** [comment]
Did you configure the 'recorder' integration and possibly add the blueiris domain to it?

**Comment by WolfsWelpe** [comment]
> Did you configure the 'recorder' integration and possibly add the blueiris domain to it?

Hello,

yes I have configured the 'recorder' integration.
I also found and orphaned Entity in my recorder include_entities list, I removed it and now it seems to be gone.
I will watch it for a few more hours, if it comes back than it was not the soluition, if not I will close this case.

I added to the include entry:

```
    entity_globs:
      - binary_sensor.blueiris_*_motion
```

Let's see if it works.

**Comment by kramttocs** [comment]
How is this looking? Did that resolve the issue?
