### ISSUE TITLE
2.0 - Switch Profiles

### ISSUE THREAD

**Issue by Mdleal** [elad-bar/ha-blueiris#24]
I can not switch profiles on the new version.  If I switch manually via BI the change does not reflect in HASS. If I reboot HASS the status syncs back up correctly but still can not change the profile via the switch.

2020-02-07 15:07:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/blueiris/home_assistant.py", line 41, in async_update
    await self._api.async_update()
AttributeError: 'NoneType' object has no attribute 'async_update'
2020-02-07 15:07:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/blueiris/home_assistant.py", line 41, in async_update
    await self._api.async_update()
AttributeError: 'NoneType' object has no attribute 'async_update'

**Comment by Mdleal** [comment]
Appears to be working after the latest update.

**Comment by elad-bar** [comment]
yes, now it's more managed but still takes place, hope that in next version will be solved
