### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

### ISSUE THREAD

**Issue by FraatTailscale** [elad-bar/ha-blueiris#240]
I just installed fresh HA, hacs, ssh . Now Im tried to install blueiris and got this error.
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

Other installations normal and HACS are working fine.

tried with with v .19 an v .18

**Comment by FraatTailscale** [comment]
Logger: aiohttp.server
Quelle: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
Erstmals aufgetreten: 12:31:51 (2 Vorkommnisse)
Zuletzt protokolliert: 12:37:01

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1322, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blueiris/config_flow.py", line 39, in async_step_user
    await self._config_flow.initialize(self.hass)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 63, in initialize
    await self.update_data(data, CONFIG_FLOW_INIT)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 97, in update_data
    await self._update_entry()
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 240, in _update_entry
    entry = ConfigEntry(
            ^^^^^^^^^^^^
TypeError: ConfigEntry.__init__() missing 1 required keyword-only argument: 'discovery_keys'

**Comment by SiteRelEnby** [comment]
Same issue here. Just migrated HA to a new host and now having this issue. Tried removing `/config/custom_components/blueiris` and reinstalling but no luck. Happy to do any advanced troubleshooting needed.

**Comment by floodwayprintco** [comment]
Yeup, same here. Fixing some network stuff and can't re-add BlueIris.

**Comment by kramttocs** [comment]
Please update the integration and let me know. Thanks

**Comment by SiteRelEnby** [comment]
Installed v1.0.20.

```
Error

Config flow could not be loaded: {"message":"Invalid handler specified"}
```

I uninstalled the addon in troubleshooting, I know I could enable debug logging if it was already installed, but is there a way to when it isn't already? Since I hit the error as part of the install workflow.

("A different error, I guess that's progress")

**Comment by SiteRelEnby** [comment]
Rather unhelpfully, restoring from the backup and freshly updating to it fixed it and options are now working for me. Sorry for the lack of a detailed logfile.

**Comment by scotttmark** [comment]
Yes, you can set debug levels in your configuration yaml for specific components. For next time :) 

Will see if others run into that.
Thanks

**Comment by kramttocs** [comment]
Yes, you can set debug levels in your configuration yaml by components. For next time :)

Thanks. Will see if others run into the same.

**Comment by kramttocs** [comment]
Just for reference:

#logger:
#  default: warning
#  logs:
#    custom_components.blueiris: debug

**Comment by floodwayprintco** [comment]
Thanks for the quick update. I got it working today. Although I did have to uninstall the andd-on and then reinstall it. The configuration was kind of hanging before that, but it might’ve been some issues with my server too. All is well!
