### ISSUE TITLE
Error adding entity binary_sensor.kavo_2024_alerts for domain binary_sensor with platform blueiris

### ISSUE THREAD

**Issue by Benj-HaRRison** [elad-bar/ha-blueiris#247]
Регистратор: homeassistant.components.binary_sensor
Источник: helpers/entity_platform.py:918
интеграция: Бинарный сенсор (документация, проблемы)
Первое сообщение: 01:45:29 (1 сообщений)
Последнее сообщение: 01:45:29

Error adding entity binary_sensor.kavo_2024_alerts for domain binary_sensor with platform blueiris
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 220, in async_subscribe_internal
    mqtt_data = hass.data[DATA_MQTT]
                ~~~~~~~~~^^^^^^^^^^^
KeyError: 'mqtt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1367, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/blueiris/models/base_entity.py", line 101, in async_added_to_hass
    await self.async_added_to_hass_local()
  File "/config/custom_components/blueiris/binary_sensors/main.py", line 59, in async_added_to_hass_local
    self.remove_subscription = await async_subscribe(
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 199, in async_subscribe
    return async_subscribe_internal(hass, topic, msg_callback, qos, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 222, in async_subscribe_internal
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot subscribe to topic 'BlueIris/+/Status', make sure MQTT is set up correctly

**Comment by kramttocs** [comment]
Did you take the action mentioned in the error?

`Cannot subscribe to topic 'BlueIris/+/Status', make sure MQTT is set up correctly`

**Comment by kramttocs** [comment]
Closing due to no response
