### ISSUE TITLE
Latest update failing

### ISSUE THREAD

**Issue by iceman73** [elad-bar/ha-blueiris#51]
I updated to the latest update today and the integration stopped working. I removed and reinstalled the integration but the setup keeps coming up as an unknown error

**Comment by elad-bar** [comment]
Can you post the log?

**Comment by iceman73** [comment]
`hal:/usr/share/hassio/homeassistant$ cat home-assistant.log | grep blue
2020-04-18 10:51:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-18 10:56:04 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
2020-04-18 10:56:26 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
  File "/config/custom_components/blueiris/config_flow.py", line 96, in async_step_user`

**Comment by iceman73** [comment]
`2020-04-18 10:51:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-18 10:56:04 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
2020-04-18 10:56:26 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
2020-04-18 10:56:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 96, in async_step_user
    host = self._config_flow.config_data.host
AttributeError: 'BlueIrisFlowHandler' object has no attribute '_config_flow'`

**Comment by iceman73** [comment]
One last log when trying to set up the integration

`2020-04-18 12:30:35 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
2020-04-18 12:30:53 DEBUG (MainThread) [custom_components.blueiris.config_flow] Starting async_step_user of blueiris
2020-04-18 12:30:53 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 96, in async_step_user
    host = self._config_flow.config_data.host
AttributeError: 'BlueIrisFlowHandler' object has no attribute '_config_flow'`

**Comment by GeneralErrors** [comment]
I am running into the same issue on a clean install - just trying to use the BlueIris integration for the first time.
