### ISSUE TITLE
"Unknown error occurred" while setting up the integration

### ISSUE THREAD

**Issue by sdwilsh** [elad-bar/ha-blueiris#81]
I have a fresh home assistant install via Home Assistant OS (HassOS 4.12, 0.114.2), and I've isntalled this addon with HACS v1.4.1, and when I'm trying to setup this integration, I get an "Unknown error occurred" when trying to submit.  The stack-trace (from the logs) is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/blueiris/config_flow.py", line 60, in async_step_user
    schema = await self._config_flow.get_default_data(new_user_input)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 120, in get_default_data
    config_data = await self._config_manager.get_basic_data(user_input)
  File "/config/custom_components/blueiris/managers/configuration_manager.py", line 66, in get_basic_data
    result.password_clear_text = await self.password_manager.decrypt(
  File "/config/custom_components/blueiris/managers/password_manager.py", line 56, in decrypt
    decrypted = self.crypto.decrypt(data.encode()).decode()
  File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 74, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 92, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by Pethson** [comment]
I have the same issue. Similar setup, but I have some other add-ons installed as well.

///Peter

**Comment by elad-bar** [comment]
Please remove the integration, restart HA and reinstall,
Did it happen on the first time you've installed and tried to integrate it or after an update?

Thanks

**Comment by Pethson** [comment]
It has never worked, It was the first time I installed and tried to configure.
I uninstalled BlueIris integration through HACS, rebooted my HassOS 4.12 running HomeAssistant 0.114.4.
Reinstalled BlueIris integration through HACS, rebooted once more.
Still the same problem...

I installed HACS for the first time on this HassOS yesterday. HACS integration version is 1.5.2

///Peter!

**Comment by elad-bar** [comment]
@Pethson please try to remove the integration (not installation) and delete the file .blueiris that available in config/.storage directory of HA,
Restart HA and try again, if it's not working, pls do it once again with log level of the component in debug and post it for me to reproduce  it

Thanks

**Comment by Pethson** [comment]
OK, I tried to remove the integration of BlueIris integration and deleted the .blueiris file. Rebooted HassOS
Added the integration again and rebooted once more. Still the same problem.
So how do I add log level, and where do I find the log file?

I'm kind of new to this as you probebly can tell...

///Peter

**Comment by Pethson** [comment]
I also tried to remove the HACS integration and deleted the .blueiris file. Rebooted, added HACS integration and rebooted....

///P

**Comment by Pethson** [comment]
Solved the problem 👍 
It was me who hade put restrictions in Bluiris not accept web access from that subnet...

///Peter

**Comment by elad-bar** [comment]
@sdwilsh please let me know if now you can reproduce it, if not, please close the bug

thanks

**Comment by sdwilsh** [comment]
Honestly, I setup BlueIris with HA manually, and I don't plan to move away from that at this time.  I'll close this out for now.
